config/routes.rb
Rails.application.routes.draw do
  get '/' => "users#index"

  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :products, only: [:index, :show, :new, :create, :destroy]
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to(:product)
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to(:user)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many(:products)

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(entry_params)
    if product.save
      redirect_to(action: 'index', controller: 'products')
    end
  end

  def entry_params
    params.require(:product).permit(:title, :description, :deadline)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(entry_params)
    if user.save
      redirect_to(action: 'index', controller: 'users')
    end
  end

  private
  def entry_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auctionsite</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Auction Marketplace</h1>
  </header>

<%= yield %>

<footer>
  <p>© Ironhack</p>
  <p>Gonzalo MV</p>
</footer>
</body>
</html>

app/views/products/index.html.erb
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to "#{product.title}", products_path %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h2>New Product</h2>

<% if @product.errors.any? %>
  <ul>
    <%= @product.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :deadline %>
  <%= f.date_field :deadline %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

<%= link_to "Cancel", products_path %>

app/views/users/index.html.erb
<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.name}", users_path %>
    </li>
  <% end %>
</ul>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>New User</h2>

<% if @user.errors.any? %>
  <ul>
    <%= @user.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br><br>
  <%= f.submit 'Save' %>
<% end %>
<br>
<%= link_to "Cancel", users_path %>